# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadi',
            name='phoneno',
            field=models.IntegerField(default=9896647535),
            preserve_default=False,
        ),
    ]
